#!/bin/bash

# Add here any the actions which are required before solution build
# like packages building, packages downloading from mirrors and so on.
# The script should return 0 if there were no errors.
